### PR TITLE
Find the Union and Intersection of the two sorted arrays

### PR DESCRIPTION
**Pull request by HPatel08**
Category C++

### CODE REVIEW

**Comment by deniss-eh** [comment]
Change location to Programs/c++

**Review by deniss-eh — CHANGES_REQUESTED** [review]
add these programs in programs/c++ folder

**Comment by deniss-eh** [comment]
You can also contribute to my new repository where you can contribute by opening pull requests for DSA related programs. :)
https://github.com/deniss-eh/DSA-HACKTOBERFEST

**Comment by HPatel08** [comment]
I made the changes, you requested.
kindly check my PR #19

**Comment by deniss-eh** [comment]
> I made the changes, you requested. kindly check my PR #19

checked and merged and now im closing this pr

**Pull request closed without merging**
