### PR TITLE
dsa problems

### LINKED ISSUE #11: Add programs related to DSA problems
edit : make sure you guys add programs in program/c++ folder if having c++ program else create new folder according to the language.

### PR DESCRIPTION
**Pull request by Teddy1404**
This closes #11

### CODE REVIEW

**Comment by deniss-eh** [comment]
add these programs in programs/c++ folder

**Review by deniss-eh — CHANGES_REQUESTED** [review]
add these programs in programs/c++ folder

**Comment by deniss-eh** [comment]
You can also contribute to my new repository where you can contribute by opening pull requests for DSA related programs. :)
https://github.com/deniss-eh/DSA-HACKTOBERFEST

**Comment by Teddy1404** [comment]
done

**Pull request merged**
